module.exports = [
  {
    name: 'Mario',
    gameId: '01',
    from: 'Super Mario',
    imageUrl: `${process.env.HOST}/images/MarioHead.png`,
  },
  {
    name: 'Donkey Kong',
    gameId: '02',
    from: 'Donkey Kong',
    imageUrl: `${process.env.HOST}/images/DonkeyKongHead.png`,
  },
  {
    name: 'Link',
    gameId: '03',
    from: 'The Legend of Zelda',
    imageUrl: `${process.env.HOST}/images/LinkHead.png`,
  },
  {
    name: 'Samus',
    gameId: '04',
    from: 'Metroid',
    imageUrl: `${process.env.HOST}/images/SamusHead.png`,
  },
  {
    name: 'Samus Sombre',
    gameId: '04e',
    from: 'Metroid',
    imageUrl: `${process.env.HOST}/images/DarkSamusHead.png`,
  },
  {
    name: 'Yoshi',
    gameId: '05',
    from: 'Yoshi',
    imageUrl: `${process.env.HOST}/images/YoshiHead.png`,
  },
  {
    name: 'Kirby',
    gameId: '06',
    from: 'Kirby',
    imageUrl: `${process.env.HOST}/images/KirbyHead.png`,
  },
  {
    name: 'Fox',
    gameId: '07',
    from: 'StarFox',
    imageUrl: `${process.env.HOST}/images/FoxHead.png`,
  },
  {
    name: 'Pikachu',
    gameId: '08',
    from: 'Pokemon',
    imageUrl: `${process.env.HOST}/images/PikachuHead.png`,
  },
  {
    name: 'Luigi',
    gameId: '09',
    from: 'Super Mario',
    imageUrl: `${process.env.HOST}/images/LuigiHead.png`,
  },
  {
    name: 'Ness',
    gameId: '10',
    from: 'EarthBound',
    imageUrl: `${process.env.HOST}/images/NessHead.png`,
  },
  {
    name: 'Capitaine Falcon',
    gameId: '11',
    from: 'F-Zero',
    imageUrl: `${process.env.HOST}/images/CaptainFalconHead.png`,
  },
  {
    name: 'Rondoudou',
    gameId: '12',
    from: 'Pokemon',
    imageUrl: `${process.env.HOST}/images/JigglypuffHead.png`,
  },
  {
    name: 'Peach',
    gameId: '13',
    from: 'Super Mario',
    imageUrl: `${process.env.HOST}/images/PeachHead.png`,
  },
  {
    name: 'Daisy',
    gameId: '13e',
    from: 'Super Mario',
    imageUrl: `${process.env.HOST}/images/DaisyHead.png`,
  },
  {
    name: 'Bowser',
    gameId: '14',
    from: 'Super Mario',
    imageUrl: `${process.env.HOST}/images/BowserHead.png`,
  },
  {
    name: 'Ice Climbers',
    gameId: '15',
    from: 'Ice Climbers',
    imageUrl: `${process.env.HOST}/images/IceClimbersHead.png`,
  },
  {
    name: 'Sheik',
    gameId: '16',
    from: 'The Legend of Zelda',
    imageUrl: `${process.env.HOST}/images/SheikHead.png`,
  },
  {
    name: 'Zelda',
    gameId: '17',
    from: 'The Legend of Zelda',
    imageUrl: `${process.env.HOST}/images/ZeldaHead.png`,
  },
  {
    name: 'Dr. Mario',
    gameId: '18',
    from: 'Super Mario',
    imageUrl: `${process.env.HOST}/images/DrMarioHead.png`,
  },
  {
    name: 'Pichu',
    gameId: '19',
    from: 'Pokemon',
    imageUrl: `${process.env.HOST}/images/PichuHead.png`,
  },
  {
    name: 'Falco',
    gameId: '20',
    from: 'StarFox',
    imageUrl: `${process.env.HOST}/images/FalcoHead.png`,
  },
  {
    name: 'Marth',
    gameId: '21',
    from: 'Fire Emblem',
    imageUrl: `${process.env.HOST}/images/MarthHead.png`,
  },
  {
    name: 'Lucina',
    gameId: '21e',
    from: 'Fire Emblem',
    imageUrl: `${process.env.HOST}/images/LucinaHead.png`,
  },
  {
    name: 'Link Enfant',
    gameId: '22',
    from: 'The Legend Of Zelda',
    imageUrl: `${process.env.HOST}/images/YoungLinkHead.png`,
  },
  {
    name: 'Ganondorf',
    gameId: '23',
    from: 'The Legend Of Zelda',
    imageUrl: `${process.env.HOST}/images/GanondorfHead.png`,
  },
  {
    name: 'Mewtwo',
    gameId: '24',
    from: 'Pokemon',
    imageUrl: `${process.env.HOST}/images/MewtwoHead.png`,
  },
  {
    name: 'Roy',
    gameId: '25',
    from: 'Fire Emblem',
    imageUrl: `${process.env.HOST}/images/RoyHead.png`,
  },
  {
    name: 'Chrom',
    gameId: '25e',
    from: 'Fire Emblem',
    imageUrl: `${process.env.HOST}/images/ChromHead.png`,
  },
  {
    name: 'Mr. Game & Watch',
    gameId: '26',
    from: 'Game & Watch',
    imageUrl: `${process.env.HOST}/images/MrGame&WatchHead.png`,
  },
  {
    name: 'Meta Knight',
    gameId: '27',
    from: 'Kirby',
    imageUrl: `${process.env.HOST}/images/MetaKnightHead.png`,
  },
  {
    name: 'Pit',
    gameId: '28',
    from: 'Kid Icarus',
    imageUrl: `${process.env.HOST}/images/PitHead.png`,
  },
  {
    name: 'Pit Maléfique',
    gameId: '28e',
    from: 'Kid Icarus',
    imageUrl: `${process.env.HOST}/images/DarkPitHead.png`,
  },
  {
    name: 'Samus Sans Armure',
    gameId: '29',
    from: 'Metroid',
    imageUrl: `${process.env.HOST}/images/ZeroSuitSamusHead.png`,
  },
  {
    name: 'Wario',
    gameId: '30',
    from: 'WarioWare',
    imageUrl: `${process.env.HOST}/images/WarioHead.png`,
  },
  {
    name: 'Snake',
    gameId: '31',
    from: 'Metal Gear',
    imageUrl: `${process.env.HOST}/images/SnakeHead.png`,
  },
  {
    name: 'Ike',
    gameId: '32',
    from: 'Fire Emblem',
    imageUrl: `${process.env.HOST}/images/IkeHead.png`,
  },
  {
    name: 'Dresseur de Pokemon',
    gameId: '33-35',
    from: 'Fire Emblem',
    imageUrl: `${process.env.HOST}/images/PokemonTrainerHead.png`,
  },
  {
    name: 'Diddy Kong',
    gameId: '36',
    from: 'Donkey Kong',
    imageUrl: `${process.env.HOST}/images/DiddyKongHead.png`,
  },
  {
    name: 'Lucas',
    gameId: '37',
    from: 'EarthBound',
    imageUrl: `${process.env.HOST}/images/LucasHead.png`,
  },
  {
    name: 'Sonic',
    gameId: '38',
    from: 'Sonic The Hedgehog',
    imageUrl: `${process.env.HOST}/images/SonicHead.png`,
  },
  {
    name: 'Roi Dadidou',
    gameId: '39',
    from: 'Kirby',
    imageUrl: `${process.env.HOST}/images/KingDededeHead.png`,
  },
  {
    name: 'Olimar',
    gameId: '40',
    from: 'Pikmin',
    imageUrl: `${process.env.HOST}/images/OlimarHead.png`,
  },
  {
    name: 'Lucario',
    gameId: '41',
    from: 'Pokemon',
    imageUrl: `${process.env.HOST}/images/LucarioHead.png`,
  },
  {
    name: 'R.O.B.',
    gameId: '42',
    from: 'R.O.B.',
    imageUrl: `${process.env.HOST}/images/ROBHead.png`,
  },
  {
    name: 'Link Cartoon',
    gameId: '43',
    from: 'The Legend Of Zelda',
    imageUrl: `${process.env.HOST}/images/ToonLinkHead.png`,
  },
  {
    name: 'Wolf',
    gameId: '44',
    from: 'StarFox',
    imageUrl: `${process.env.HOST}/images/WolfHead.png`,
  },
  {
    name: 'Villageois',
    gameId: '45',
    from: 'Animal Crossing',
    imageUrl: `${process.env.HOST}/images/VillagerHead.png`,
  },
  {
    name: 'Mega Man',
    gameId: '46',
    from: 'Mega Man',
    imageUrl: `${process.env.HOST}/images/MegaManHead.png`,
  },
  {
    name: 'Entraîneuse Wii-Fit',
    gameId: '47',
    from: 'Wii-Fit',
    imageUrl: `${process.env.HOST}/images/WiiFitTrainerHead.png`,
  },
  {
    name: 'Rosalina',
    gameId: '48',
    from: 'Super Mario',
    imageUrl: `${process.env.HOST}/images/RosalinaHead.png`,
  },
  {
    name: 'Little Mac',
    gameId: '49',
    from: 'Punch-Out!!',
    imageUrl: `${process.env.HOST}/images/LittleMacHead.png`,
  },
  {
    name: 'Amphinobi',
    gameId: '50',
    from: 'Pokemon',
    imageUrl: `${process.env.HOST}/images/GreninjaHead.png`,
  },
  {
    name: 'Combattant Mii',
    gameId: '51-53',
    from: 'Mii',
    imageUrl: `${process.env.HOST}/images/MiiFighterHead.png`,
  },
  {
    name: 'Paluténa',
    gameId: '54',
    from: 'Kid Icarus',
    imageUrl: `${process.env.HOST}/images/PalutenaHead.png`,
  },
  {
    name: 'Pac-Man',
    gameId: '55',
    from: 'Pac-Man',
    imageUrl: `${process.env.HOST}/images/Pac-ManHead.png`,
  },
  {
    name: 'Robin',
    gameId: '56',
    from: 'Fire Emblem',
    imageUrl: `${process.env.HOST}/images/RobinHead.png`,
  },
  {
    name: 'Shulk',
    gameId: '57',
    from: 'Xenoblade Chronicles',
    imageUrl: `${process.env.HOST}/images/ShulkHead.png`,
  },
  {
    name: 'Bowser JR.',
    gameId: '58',
    from: 'Super Mario',
    imageUrl: `${process.env.HOST}/images/BowserJrHead.png`,
  },
  {
    name: 'Duck Hunt',
    gameId: '59',
    from: 'Duck Hunt',
    imageUrl: `${process.env.HOST}/images/DuckHuntHead.png`,
  },
  {
    name: 'Ryu',
    gameId: '60',
    from: 'Street Fighter',
    imageUrl: `${process.env.HOST}/images/RyuHead.png`,
  },
  {
    name: 'Ken',
    gameId: '60e',
    from: 'Street Fighter',
    imageUrl: `${process.env.HOST}/images/KenHead.png`,
  },
  {
    name: 'Cloud',
    gameId: '61',
    from: 'Final Fantasy VII',
    imageUrl: `${process.env.HOST}/images/CloudHead.png`,
  },
  {
    name: 'Corrin',
    gameId: '62',
    from: 'Fire Emblem',
    imageUrl: `${process.env.HOST}/images/CorrinHead.png`,
  },
  {
    name: 'Bayonetta',
    gameId: '63',
    from: 'Bayonetta',
    imageUrl: `${process.env.HOST}/images/BayonettaHead.png`,
  },
  {
    name: 'Inkling',
    gameId: '64',
    from: 'Splatoon',
    imageUrl: `${process.env.HOST}/images/InklingHead.png`,
  },
  {
    name: 'Ridley',
    gameId: '65',
    from: 'Metroid',
    imageUrl: `${process.env.HOST}/images/RidleyHead.png`,
  },
  {
    name: 'Simon',
    gameId: '66',
    from: 'Castlevania',
    imageUrl: `${process.env.HOST}/images/SimonHead.png`,
  },
  {
    name: 'Richter',
    gameId: '66e',
    from: 'Castlevania',
    imageUrl: `${process.env.HOST}/images/RichterHead.png`,
  },
  {
    name: 'Roi K. Rool',
    gameId: '67',
    from: 'Donkey Kong',
    imageUrl: `${process.env.HOST}/images/KingKRoolHead.png`,
  },
  {
    name: 'Marie',
    gameId: '68',
    from: 'Animal Crossing',
    imageUrl: `${process.env.HOST}/images/IsabelleHead.png`,
  },
  {
    name: 'Félinferno',
    gameId: '69',
    from: 'Pokemon',
    imageUrl: `${process.env.HOST}/images/IncineroarHead.png`,
  },
  {
    name: 'Fleur Piranha',
    gameId: '70',
    from: 'Super Mario',
    imageUrl: `${process.env.HOST}/images/PiranhaPlantHead.png`,
  },
  {
    name: 'Joker',
    gameId: '71',
    from: 'Persona 5',
    imageUrl: `${process.env.HOST}/images/JokerHead.png`,
  },
  {
    name: 'Héros',
    gameId: '72',
    from: 'Dragon Quest',
    imageUrl: `${process.env.HOST}/images/HeroHead.png`,
  },
  {
    name: 'Banjo & Kazooie',
    gameId: '73',
    from: 'Banjo & Kazooie',
    imageUrl: `${process.env.HOST}/images/Banjo&KazooieHead.png`,
  },
  {
    name: 'Terry',
    gameId: '74',
    from: 'Fatal Fury',
    imageUrl: `${process.env.HOST}/images/TerryHead.png`,
  },
  {
    name: 'Byleth',
    gameId: '75',
    from: 'Fire Emblem',
    imageUrl: `${process.env.HOST}/images/BylethHead.png`,
  },
  {
    name: 'Min Min',
    gameId: '76',
    from: 'Arms',
    imageUrl: `${process.env.HOST}/images/MinMinHead.png`,
  },
  {
    name: 'Steve',
    gameId: '77',
    from: 'Minecraft',
    imageUrl: `${process.env.HOST}/images/SteveHead.png`,
  },
  {
    name: 'Sephiroth',
    gameId: '78',
    from: 'Final Fantasy VII',
    imageUrl: `${process.env.HOST}/images/SephirothHead.png`,
  },
  {
    name: 'Pyra',
    gameId: '79-80',
    from: 'Xenoblade Chronicles',
    imageUrl: `${process.env.HOST}/images/PyraHead.png`,
  },
]
